image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ./mvnw clean package

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - ./mvnw test